# Static Web Deployment Inventory
# Assignment 35 - Multi-Play Structure

[web]
4.206.19.198  # ansible-vm-0 (was web tier)
4.205.118.105   # ansible-vm-1 (was app tier)
13.71.165.48     # ansible-vm-2 (was db tier)

[web:vars]
ansible_user=azureuser
ansible_ssh_private_key_file=~/.ssh/id_rsa_azure
ansible_python_interpreter=/usr/bin/python3
